spring.application.name=daylenge

# PostgreSQL
spring.datasource.url=jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# App
server.port=${PORT:8080}

# JWT
jwt.secret=${JWT_SECRET:daylenge-super-geheimer-schluessel-mindestens-32-zeichen}
jwt.expiration=${JWT_EXPIRATION:86400000}